gridsync/gridsync

gridsync/gui/share.py

Complete invite on SetupRunner's 'done' Signal

---

gridsync/__init__.py
gridsync/desktop.py
gridsync/gui/preferences.py
tests/test_desktop.py

Add option to launch application on login

---

gridsync/gui/share.py
gridsync/tahoe.py
tests/test_tahoe.py

57.concurrent invites

---

appveyor.yml
make.bat
misc/Gridsync.iss

Add Windows executable installer

---

gridsync/gui/view.py

Show error if trying to restore from missing caps

---

gridsync/core.py

Just a couple of very minor adjustments that probably should have been included in #161

Start message tweaks

---

gridsync/__init__.py
gridsync/desktop.py
tests/test_desktop.py

Unset LD_LIBRARY_PATH when running frozen

---

gridsync/invite.py
tests/test_invite.py

185.reject invalid cheatcodes

---

.travis.yml
Makefile
appveyor.yml
make.bat
tox.ini

175.python3.7

---

gridsync/gui/status.py

Always show menu button

---

gridsync/gui/__init__.py

205.refocus on open

---

gridsync/gui/systray.py

209.activate on notification click win32

---

gridsync/config.py
gridsync/desktop.py
gridsync/gui/debug.py
gridsync/news.py
gridsync/recovery.py
gridsync/setup.py
gridsync/tahoe.py
requirements/requirements-gridsync.txt
setup.py

212.atomic writes

---

gridsync/gui/model.py
gridsync/gui/preferences.py

Closes #218 
Also, some very minor cleanups.

Disable desktop notifications for connection events by default

---

gridsync/setup.py

Only call ensure_recovery() for newly-joined grids

---

gridsync/gui/view.py

Catch KeyError for not-yet-loaded magic-folder directories

---

gridsync/gui/view.py

Another instance of Issue #224; this was missed previously in PR #225

Catch KeyError in open_path() call

---

gridsync/core.py

Fix workaround for high-DPI scaling issue on Qubes-OS

---

tests/test___init__.py

Fix config_dir tests to test against APP_NAME instead of hardcoded string

---

.travis.yml
setup.py
tox.ini
vagrantfiles/linux/Vagrantfile
vagrantfiles/macos/Vagrantfile
vagrantfiles/windows/Vagrantfile

Drop Python 3.5 support; require Python 3.6+

---

gridsync/core.py
gridsync/desktop.py
tests/test_desktop.py

Fix autostart functionality for AppImages

---

gridsync/gui/view.py

Unselect folders on "Action" button left-click

---

gridsync/gui/debug.py
tests/gui/test_debug.py

Remove scroll-to-bottom requirement for debug log

---

requirements/pyinstaller.txt
scripts/make_appimage.py

Fix AppImages with PyInstaller version 3.6

---

misc/gridsync.spec

Add "pkg_resources.py2_warn" to hidden imports

---

misc/gridsync.spec

Disable LSBackgroundOnly, LSUIElement on macOS by default

---

.travis.yml
Makefile
README.rst
Vagrantfile
make.bat
scripts/provision_buildbot-worker.ps1
scripts/provision_buildbot-worker.sh
scripts/provision_devtools.bat
scripts/provision_devtools.sh

This PR consolidates the `Vagrantfile`s in `vagrantfiles/` into one, top-level `Vagrantfile` and splits out some provisioning steps into separate, standalone scripts for easier maintenance.

Consolidate Vagrantfiles

---

gridsync/tahoe.py
tests/test_tahoe.py

Remove stale magic-folder sqlite databases on exit/restart on Windows

---

.github/workflows/ci.yaml
scripts/provision_devtools.sh

Configure and enable GitHub Actions for CI

---

.github/workflows/ci.yaml
.travis.yml
Makefile
scripts/provision_devtools.bat
scripts/provision_devtools.sh
setup.py
tox.ini

306.python3.9 support

---

Makefile
misc/dmgbuild_settings.py
requirements/dmgbuild.txt

Fix "dmg" make target / unbreak dmgbuild

---

Makefile
make.bat
misc/rsa-public-exponent.patch

Backport Tahoe-LAFS "cryptography" fix

---

misc/tahoe.spec

Fixes https://github.com/gridsync/gridsync/issues/313

Suppress tahoe's CryptographyDeprecationWarning

---

.github/workflows/ci.yaml
gridsync/__init__.py
scripts/provision_devtools.sh

Set QT_MAC_WANTS_LAYER=1 on macOS/darwin

---

docs/cheat-codes.md
gridsync/resources/providers/hro-cloud.json

Add grid configuration for Least Authority's "HRO Cloud"

---

Makefile
requirements/pyinstaller.txt

Update PyInstaller to version 4.3

---

gridsync/gui/toolbar.py

Emit correct pyqtSignal for "Create Invite Code" action

---

.github/workflows/ci.yaml
gridsync/crypto.py
gridsync/msg.py
gridsync/network.py
gridsync/system.py
gridsync/tahoe.py
setup.cfg
tests/conftest.py
tests/integration/test_tahoe_integration.py
tests/test_crypto.py
tests/test_network.py
tests/test_system.py
tox.ini

This PR contains a number of miscellaneous functions and test fixtures, parts of which are common to several in-progress branches (`mobile-gateway-bridge.3`, `290.new-magic-folder`) and most of which are intended to facilitate integration testing. Merging these changes into `master` early/now will ease ongoing maintenance and development burdens, reduce the need to duplicate efforts, and result in smaller diffs between branches later on.

Common functions and fixtures

---

gridsync/filter.py
gridsync/recovery.py
gridsync/setup.py
gridsync/tahoe.py
tests/conftest.py
tests/integration/test_tahoe_integration.py
tests/test_setup.py
tests/test_tahoe.py

Preserve and restore convergence secret during recovery

---

gridsync/core.py

Set a PassThrough HighDpiScaleFactorRoundingPolicy

---

gridsync/recovery.py
tests/test_recovery.py

Improve error-handling for importing Recovery Keys

---

gridsync/voucher.py
tests/test_voucher.py

Handle non-ASCII characters in voucher codes

---

Makefile
misc/gridsync.spec
requirements/pyinstaller.txt

Update PyInstaller to version 4.4; fix reproducible builds

---

gridsync/__init__.py
gridsync/gui/main_window.py
gridsync/gui/preferences.py
gridsync/gui/toolbar.py
gridsync/gui/view.py
gridsync/tor.py
tests/test_tor.py

Feature flag fixes

---

nix/default.nix
nix/pyqtchart.nix

See #378.
I've not actually run this, but it does build.
cc: @exarkun

Update pyqtchart nix expression.

---

tox.ini

Fix PyInstaller builds on GitHub Actions Windows environment

---

gridsync/tahoe.py
tests/test_tahoe.py

Correctly handle "allowed-public-keys" ZKAPAuthorizer values

---

Makefile
make.bat
misc/tahoe.py
misc/tahoe.spec
requirements/tahoe-lafs.txt

Don't clone tahoe

---

.github/workflows/ci.yaml
gridsync/magic_folder.py
gridsync/system.py
gridsync/tahoe.py
misc/gridsync.spec
tests/integration/test_magic_folder_integration.py
tests/integration/test_tahoe_integration.py
tests/test_system.py

Prepend application name to bundled `tahoe` and `magic-folder` executables

---

gridsync/gui/usage.py
gridsync/monitor.py
tests/gui/test_usage.py
tests/test_monitor.py

Surface "redeeming" state in ZKAPs/"Storage-time" view

---

requirements/gridsync.in
setup.py

Copy -- and loosen -- requirements in setup.py

---

gridsync/core.py
gridsync/gui/debug.py

Add explicit timezone information to debug log

---

gridsync/recovery.py

Warn about data-loss -- and get user-confirmation -- when restoring from Recovery Key

---

gridsync/gui/view.py

Display dialog when trying to add empty folders

---

Vagrantfile
scripts/provision_sac.ps1

This PR provides some minor updates to the project `Vagrantfile` -- adding Ubuntu 22.04, fixing a WinRM issue on newer hosts, and adding a "sac" provision target to install the SafeNet Authentication Client for MS Authenticode signing on Windows.

Vagrantfile updates

---

gridsync/gui/welcome.py
gridsync/setup.py
gridsync/zkapauthorizer.py

@crwood client-side of https://github.com/PrivateStorageio/ZKAPAuthorizer/pull/410

use the websocket endpoint for recovery

---

gridsync/gui/main_window.py

Fix default filename suffix for unencrypted Recovery Keys

---

.github/workflows/ci.yaml
README.rst

See https://github.com/actions/virtual-environments/issues/5583
Closes https://github.com/gridsync/gridsync/issues/510

Drop `macos-10.15` from GitHub Actions matrix

---

gridsync/magic_folder.py
gridsync/rootcap.py
gridsync/tahoe.py
gridsync/zkapauthorizer.py
tests/integration/test_magic_folder_integration.py
tests/integration/test_rootcap_integration.py
tests/test_setup.py
tests/test_tahoe.py

Replace `inlineCallbacks` with `async def` in gridsync/rootcap.py

---

gridsync/core.py
gridsync/gui/view.py
gridsync/magic_folder.py
gridsync/monitor.py
gridsync/tahoe.py
gridsync/types.py
gridsync/zkapauthorizer.py
tests/integration/test_magic_folder_integration.py

Convert magic_folder.py to `async def`

---

gridsync/resources/providers/hro-cloud.json

HRO cloud upgrade Gridsync configs

HRO clould upgrade configs

---

gridsync/gui/status.py
gridsync/gui/usage.py
gridsync/monitor.py
tests/gui/test_status.py
tests/gui/test_usage.py

Handle `OverflowError` for `days_remaining_updated` Signal/Slot

---

.github/workflows/ci.yaml
README.rst

Drop support for Ubuntu 18.04

---

gridsync/resources/providers/hro-cloud.json

Update "HRO Cloud" grid-configuration

---

CHANGELOG.md
gridsync/websocket.py

Don't always/unconditionally log Magic-Folder "status" API websocket messages

---

scripts/make_appimage.py

Fix AppImage builds with latest version of `linuxdeploy`

---

Makefile
scripts/codesign.py
scripts/notarize.py

Switch to using `notarytool` for macOS notarization

---

requirements/tahoe-lafs-base.txt
requirements/tahoe-lafs.in

Remove version-pin for `python-challenge-bypass-ristretto`

---

gridsync/resources/providers/hro-cloud.json

update HRO clould configs after replacing the failing storage003 node

update HRO clould configs after replacing the failing node

---

scripts/provision_devtools.bat
scripts/provision_devtools.sh
setup.py
tox.ini

Drop Python 3.9 support

---

.github/workflows/ci.yaml

Unbreak Windows CI

---

gridsync/gui/invite.py
gridsync/gui/magic_folder.py

Adjust `MagicFolderInviteDialog`/`InviteCodeBox`

---

scripts/make_appimage.py

Add `libwayland-client.so.0` to `LD_PRELOAD`

---

gridsync/gui/menu.py
tests/gui/test_menu.py

Fix "About" dialog crash under Qt6

---

CHANGELOG.md
gridsync/gui/toolbar.py
tests/gui/test_toolbar.py

Always enable "Restore from Recovery Key" toolbar button menu action

---

.github/workflows/ci.yaml

Unpin/upgrade tox on Windows

---

gridsync/monitor.py
tests/test_monitor.py

Fix datetime `TypeError`

---

gridsync/gui/main_window.py
gridsync/recovery.py

Remove unused/unlabeled QProgressDialog buttons

---

.github/workflows/ci.yaml
misc/dmgbuild_settings.py

Increase `dmgbuild` volume size

---

.github/workflows/ci.yaml

Remove `macOS-12` from GitHub Actions matrix

---

.github/workflows/ci.yaml

Update `actions/cache` to "v4"

---

CHANGELOG.md
gridsync/resources/providers/test-grid.json

Update fURL to public test grid
