gridsync/gridsync

- gridsync/gui/setup.py
- gridsync/gui/share.py
- gridsync/setup.py
Previously, when accepting grid invites through the initial setup dialog, Gridsync would always prompt for a rename if the target nodedir existed, leading to the problems described in Issue #68. This PR updates post-invite/pre-setup behavior to prompt for a grid rename if and only if the target nodedir already exists but the introducer fURL differs (thereby re-using the existing client instance unless the introducer is actually different) and shows an informational message to users to inform them that that they have already joined the grid in question.
Fixes #68
> Fix grid name confilct issues

- .pylintrc
- gridsync/setup.py
- gridsync/tahoe.py
- tests/test_tahoe.py
This PR adds support for reading/writing storage fURLs from/to `$nodedir/private/servers.yaml` directly and allows for grids to be joined via invite codes without the need to specify an introducer fURL.
Closes #65
> 65.introducerless mode

- gridsync/gui/model.py
- gridsync/monitor.py
Otherwise, since PyQt uses C++ types, this can cause overflows
Fixes #78
> Don't pass size ints through pyqtSignal/pyqtSlot

- gridsync/gui/welcome.py
- gridsync/recovery.py
* Allow recovery keys to be imported directly from welcome page
* Allow immediate passphrase retries if decryption fails
* Begin setup immediately after import instead of requiring confirmation
Closes #60
> 60.improve restoration ux

- Makefile
- make.bat
macOS will still need to build from a separate branch until ticket 1432
is closed.
> Upgrade Tahoe-LAFS to 1.13.0 on Windows/Linux

- Makefile
- misc/gridsync.spec
Now that PyInstaller [respects Info.plist options](https://github.com/pyinstaller/pyinstaller/pull/3566), it can be used to deploy Gridsync binaries which properly launch as "agent"/background processes. Accordingly, this PR compiles the appropriate PyInstaller bootloaders on macOS at build time to enable this functionality, and creates the appropriate "Gridsync.app" bundle using PyInstaller (replacing "py2app"). I've kept the "py2app" setup options in place for now in the event that a "py2app" bundle is still needed/wanted (however, these may be removed at a future date).
> Deploy PyInstaller binaries on macOS

- gridsync/gui/model.py
- gridsync/gui/view.py
- gridsync/monitor.py
- gridsync/tahoe.py
- tests/test_monitor.py
This PR adds a number of improvements to the "monitor" module and associated functionality, including:
- Decomposing the `Monitor` class into `GridChecker` and `MagicFolderChecker` classes
- Tracking the authorship of individual changes made per magic-folder
- Tracking the type of individual changes made ("added", "updated", "deleted", "restored")
- Tracking per-sync transfer-related statistics (bytes transferred/total, speed of transfer, estimated time-remaining)
- Batching desktop notifications by author name and type
- Deduplicating buffered desktop notifications
- Scanning for untracked changes after "syncing" phase ends
- Fixing issues related to desktop notification buffering and delays
- Increasing module test-coverage to 100%
Note that although the improved Monitor module/class …
> Monitor improvements

- Makefile
- make.bat
With the upstream release of PyInstaller 3.4, bootloaders should no
longer need to be recompiled in order to have Gridsync run as an "agent"
process on macOS. See also #112.
> Update PyInstaller to 3.4

- gridsync/gui/main_window.py
This PR updates the toolbar in accordance with the suggestions listed in #106, separating submenu items into standalone buttons and adding text beneath them:
Although the icons themselves (and probably the labels too) still leave much to be desired, this change should at least make some of the functionality provided by the existing toolbar slightly more clear and accessible..
> 106.improve toolbar

- gridsync/desktop.py
- gridsync/gui/history.py
- gridsync/gui/view.py
- tests/gui/test_history.py
- tests/test_desktop.py
This PR adds an "open_enclosing_folder" function (selecting/revealing the given `path` in macOS' _Finder_ or Windows' _Explorer_), renames the existing "open_folder" function to "open_path", and adds proper tests for both functions.
> Desktop improvements

- gridsync/gui/invite.py
- gridsync/gui/main_window.py
- gridsync/gui/share.py
- gridsync/gui/view.py
- gridsync/gui/welcome.py
- gridsync/tor.py
- tests/test_tor.py
This PR adjusts the MainWindow folders-view contents margins to an explicit/standard 11 px and updates numerous QMessageBox instances to set/use the `informativeText` property (resulting in appearances which should more closely match [Apple's Human Interface Guidelines for macOS Alerts](https://developer.apple.com/design/human-interface-guidelines/macos/windows-and-views/alerts/)).
> macOS tweaks

- gridsync/gui/main_window.py
This change updates the MainWindow.populate method to behave in a more
"additive" manner: calling it will no longer clear/re-create the
associated QComboBox items and folders/history views widgets, thereby
fixing the bug which required users to re-start the application in the
event of joining a new grid via the Welcome dialog due to disconnected
Qt Signals/Slots. In addition, adding a new grid will now select it
immediately in the combobox, making it more obvious that the new grid
has been joined and facilitating adding new folders afterward.
> Fix MainWindow 'populate' method

- gridsync/gui/invite.py
Without this, pressing Tab on an InviteCodeWidget will switch focus to
the Tor info-button, thereby breaking tab-completion for invite-codes.
> Fix Tor info-button focus-policy; use Qt.NoFocus

- gridsync/gui/share.py
- gridsync/gui/welcome.py
As suggested by #98, there is little need to have the user click
"finish" or "done" buttons after setup operations have completed.
Instead, click/close such buttons/dialogs automatically when done.
Closes #98
> Remove redundant "finish"/"done" button clicks

- gridsync/gui/model.py
- gridsync/monitor.py
Due to persisting bugs in tahoe's magic-folder status queue (which often displays inaccurate information or otherwise fails to reflect the number or state of queued upload/download operations), this PR (temporarily?) disables sync progress indicators from being displayed in the UI. Users needing to get a (very) rough sense of sync progress can still do so by watching the "size" status column (which increases as new files finish uploading), the newly-added "History" tab (which populates as files are added, updated, or removed), or the debug log (which now periodically prints the total progress and time remaining values as calculated from the magic-folder queue).
Proper status indicators will be re-implemented if/when the corresponding magic-folder bugs are fixed upstream (and/or when I …
> Disable sync progress indicators

- gridsync/gui/model.py
- gridsync/gui/share.py
- gridsync/monitor.py
- tests/test_monitor.py
This PR updates how the "shared" status of a given folder is determined. More specifically, it changes the MagicFolderChecker class/QObject to emit a `members_updated` signal (replacing `member_added`, `member_removed`) which passes a list of currently known members to the folder status `Model` class. The `Model`, in turn, updates the UI to display the "shared" emblem/overlay if the list contains more than one member and removes it (thus setting the status to "private") if it contains only one. Previously, the `Model` tracked membership numbers by way of an integer mapped to each folder name, however this was mistakenly being incremented too often (specifically, when re-scanning a remote folder after it had been removed/deactivated) and was never decremented (thus the status would be …
> Fix "shared" folder emblems

- gridsync/gui/welcome.py
- gridsync/resources/config.txt
Just a couple of minor tweaks to better facilitate whitelabel builds: set the icon and slogan/description from `config.txt` and smoothen the resultant image when scaling to help prevent visual jaggedness.
> Whitelabel fixes

- Makefile
- misc/tahoe.spec
A couple of small tweaks to support using the `codesign` utility macOS: trim seemingly-superfluous files from Tahoe-LAFS bundles and add `codesign-app`, `codesign-dmg`, and `codesign-all` make targets to facilitate future releases.
Should (hopefully) close #20...
> macOS codesigning

- gridsync/cli.py
- gridsync/core.py
- gridsync/errors.py
- gridsync/lock.py
- tests/test_lock.py
A fix/workaround for the issue described in #138: rather than listening on port 52045 to provide a quick-and-dirty interprocess mutex that works across platforms, this PR instead leverages the python standard library's [`fcntl.flock()`](https://docs.python.org/3/library/fcntl.html#fcntl.flock) to provide a filesystem-based exclusive locking mechanism on UNIX-like systems (falling back to keeping an open file descriptor on Windows to provide similar -- but not wholly equivalent -- functionality), thereby preventing the situation in which Gridsync would sometimes erroneously throw a user-facing "Gridsync is already running" error message on certain macOS Mojave configurations (caused, it seems, from security/sandbox policies that might prevent listening/binding on ports).
> 138.filesystem lock

- gridsync/gui/welcome.py
This adds support for specifying a 'logo_icon' application setting via
'config.txt'. If 'logo_icon' is set to a resource file, that file will
be loaded/displayed on the initial "Welcome" screen in place of the
'tray_icon'. In addition, if a 'logo_icon' is set, hide the application
description/slogan (since "logos", by definition, contain a "mark" and a
"type" -- i.e., an image and text combination -- and so we probably
don't want/need the description/slogan text)
> Add support for specifying a "logo" via config.txt

- gridsync/tahoe.py
- tests/test_tahoe.py
This PR fixes #149 by keeping track of the run-state of the tahoe client and aborting subsequent `restart` operations if the client is already in a "stopping" or "starting" state (thereby preventing needless restarts when adding folders in quick succession).
> 149.tahoe restart fix

- make.bat
This PR excludes the Tcl/Tk libraries from the included Tahoe-LAFS binary bundle (which are needlessly included by PyInstaller) on Windows, reducing the total filesize of the application on-disk by about 10 MB. Note that Tcl/Tk is already excluded for macOS and Linux binary distributions; this PR merely updates the Windows build script to use the same/correct PyInstaller ".spec" file (which, apparently, I forgot to do earlier).
> Use updated .spec file for Tahoe; exclude Tcl/Tk

- gridsync/gui/__init__.py
- gridsync/gui/systray.py
- gridsync/gui/welcome.py
This PR updates the "Open Gridsync" systray menu action to always be enabled but to conditionally raise and show the "welcome" dialog in the event that a grid has not yet been joined, thereby allowing users to more easily access the application window from the systray before the initial setup process has completed.
Fixes #147
> 147.refocus welcome

- gridsync/gui/main_window.py
- gridsync/gui/welcome.py
- gridsync/lock.py
- gridsync/tahoe.py
This prevents the icon from persisting in the system tray after the
processs has terminated. Fixes #156.
> Hide/remove systray icon before exiting on Windows

- gridsync/tahoe.py
This PR updates the "tahoe" module's `select_executable()` logic to _always_ use the bundled Tahoe-LAFS executable in the event that the user is running a frozen/binary build, thereby preventing problems stemming from another, potentially broken or outdated Tahoe-LAFS installation on the user's PATH interfering with the operation of the application. As a bonus, the application startup time should be shortened by a second or two (as a result of no longer having to probe the other `tahoe` instances on the PATH).
Users still wishing to use their own tahoe installs with Gridsync can still do so by running the application from source or in a python virtual environment and/or by replacing the PyInstaller bundle in the `Tahoe-LAFS` directory with one their own.
> Always use bundled tahoe executable if frozen

- gridsync/core.py
This PR adds support for (optionally) displaying a popup message to the user when first launching the application. Specifically, with this change, Gridsync will check for a `[message]` section in `config.txt` when starting up and, if it is found, display a `QMessageBox` to the user with the `title`, `text`, and (icon) `type` specified by that section (where `type` is one of "information", "warning", or "critical") -- for example:
```
[message]
type = information
title = Cat Fact 8413 
text = Cats have been domesticated for around 4,000 years
```
Silly example aside, the purpose of this change is to allow whitelabel/rebranded distributions of Gridsync to display custom messages/reminders to their users (for example, about where to obtain an invite code or about who to contact for further …
> Custom start message

- gridsync/config.py
- gridsync/gui/view.py
Similar to the fixes relating to folder-creation and linking from #160, this PR provides a few minor improvements relating to folder-removal and unlinking, specifically:
* Show (slightly) more "humanized" error messages for failures/exceptions that occur while removing or unlinking a folder
* Schedule a `tahoe restart` after successfully leaving one or more magic-folders (in order to compensate for Tahoe-LAFS' ["Zombie Dragon" issue](https://tahoe-lafs.org/trac/tahoe-lafs/ticket/2996))
* Schedule a rootcap rescan _after_ unlinking one or more folders (instead of possibly during)
* Fix a weird issue in which `RawConfigParser` was erroneously caching old values from `tahoe.cfg` even after `tahoe magic-folder leave` had modified it causing folders to appear to be stuck in a "Loading..." …
> Folder removal improvements

- gridsync/gui/systray.py
This simple PR updates the logic underlying the `gridsync.systray.Menu.populate` method to only add the "Browse Documentation" and "Report Issue" help submenu items in the event that `docs_url` and `issues_url` are defined in the `[help]` section of `config.txt`. Since Gridsync _does_ define these values, this doesn't change anything from a current user-facing perspective, however, it allows custom/whitelabel builds of Gridsync to more easily omit one or both actions in the future.
> Make docs/issues URLs and their actions optional

- gridsync/wormhole_.py
- tests/test_wormhole.py
This PR updates the behavior of the `gridsync.wormhole_.Wormhole` QObject/wrapper to delay creating the underlying `wormhole` object (from the magic-wormhole library) until `Wormhole.connect()` is called. This fixes the situation in which Gridsync/magic-wormhole would needlessly open an idle connection to the relay/rendezvous server during initialization (despite not actually _using_ that connection -- thankfully -- in the event that the user enables Tor).
Fixes #169 
Big thanks to @abmoka for noticing this!
> 169.tor proxy bypass

- Makefile
- gridsync/monitor.py
- gridsync/streamedlogs.py
- gridsync/tahoe.py
- make.bat
- setup.py
- tests/conftest.py
- tests/test_monitor.py
- tests/test_streamedlogs.py
- tests/test_tahoe.py
Fixes #173
Well, it sort-of fixes it.  It only gathers the logs into the GridSync process.  It doesn't expose them to anyone in any way.  I imagine there should be a follow-up to #173 that describes some specific user experience involving this data.
> 173.consume tahoe lafs eliot logs

- gridsync/cli.py
- gridsync/core.py
- gridsync/gui/debug.py
- gridsync/gui/main_window.py
- gridsync/gui/view.py
- gridsync/msg.py
A follow-up to #179, this PR changes the `gridsync.msg` module to no longer automatically log every message that's shown to users, and adds distinct/explicit `logging.info`, `logging.critical`, `logging.error` calls in places where logging is actually desired. Distinguishing between these two types of messages -- i.e., `QMessageBox`-based messages and `logging`-based messages -- allows potentially sensitive information (such as folder names, paths, etc.) to be shown in the former, while omitting it from the latter. Normal, user-facing "error" messages that are shown as a result of a user trying to add a file instead of a folder or a folder which already exists, for example, will thus no longer result in the names of those files/folders also showing up in the logs.
> Disable qmessagebox logging

- gridsync/gui/history.py
- gridsync/gui/main_window.py
- gridsync/gui/menu.py
- gridsync/gui/status.py
- gridsync/gui/systray.py
- tests/gui/test_history.py
- tests/gui/test_status.py
This PR fixes #178 by decoupling the system tray menu from the system tray icon itself: in the event that the application is being run under a desktop environment that does _not_ support a system tray (such as the latest vanilla version of GNOME), a gear/cog button will appear in the bottom-right corner of the status panel which, when clicked, will display the menu that was previously inaccessible.
For users of desktop environments that _do_ support a system tray (including macOS, Windows, Ubuntu and, seemingly, every other commonly-used Linux distro/environment), this changes nothing: the menu will continue to be accessible from the system tray, as expected.
> 178.systray menu fallback

- misc/gridsync.spec
> Exclude libstdc++ from Linux PyInstaller bundles

- gridsync/tahoe.py
- tests/test_tahoe.py
The threaded `subprocess.Popen` workaround/hack that this PR removes is no longer necessary, as Twisted now -- and by default -- suppresses console windows for win32 subprocesses. See: https://github.com/twisted/twisted/pull/697
> Use Twisted's reactor.spawnProcess() on win32

- gridsync/gui/model.py
The systray icon will animate so long as a gateway+folder tuple is found in the `gui.core.operations` list. This one-line PR updates `Model.remove_folder` to also call `Model.on_syncing_finshed`, thereby ensuring that removed folders are always also removed from the `operations` list -- and thereby stopping the systray icon from endlessly spinning/animating in the event that the folder gets removed before the syncing operation naturally completes.
Fixes #197
> Remove folder from 'operations' list upon removal

- gridsync/core.py
A minor follow-up/addendum to PR #199: after further testing, setting this attribute to `True` globally seems to produce no ill consequences on GNU/Linux on low-resolution displays (but keeping it set to `False` when the `QT_SCALE_FACTOR` env var is `2` or greater results in "blocky" pixmaps).
Note that this change does _not_ address the issue(s) described in #198: Qt's `AA_EnableHighDpiScaling` is broken on Qubes-OS and does nothing to upscale window-sizes in conjunction with GNOME's display scale setting (at least on a 1080p display).
> Always enable Qt.AA_UseHighDpiPixmaps

- gridsync/core.py
Further/extensive testing by someone who actually uses high-DPI monitor has indicated that enabling `AA_EnableHighDpiScaling` (via the `QT_AUTO_SCREEN_SCALE_FACTOR` environment variable) works and "is a must" on GNOME as well as a number of other desktop environments (including Budgie, Cinnamon, Deepin, KDE, and XFCE). The only exception to this, reportedly, was MATE -- which, I've been told, works/looks better with auto-scaling disabled...
Accordingly, this PR enables on auto-scaling for all platforms/environments _except for_ MATE and Qubes-OS (which, as mentioned in the in-code comment, continues to apply inconsistently).
Note that Qt's auto-scaling can still be enabled or disabled by setting the `QT_AUTO_SCREEN_SCALE_FACTOR` environment variable to `1` or `0` (respectively), allowing …
> Enable Qt's high-DPI scaling on Linux

- gridsync/gui/main_window.py
- gridsync/util.py
- tests/test_util.py
A minor follow-up/improvement to #192: Qt5's `QMessageBox` will correctly render HTML tags included in newscap messages but native desktop notification popup windows will not. In order to make the text in desktop notification popup windows render similarly to the text shown in QMessageBoxes, this PR replaces HTML `<p>` tags with newlines and strips other tags from newscap messages (using the python standard library's `html.parser.HTMLParser`), thereby preventing un-rendered HTML from showing up in desktop notifications.
> Strip HTML tags from newscap notification messages

- gridsync/gui/main_window.py
This removes the default context menu on toolbars that allows them
to be shown/hidden, thereby ensuring that the the toolbar remains
visible at all times.
Closes #215
> Disable MainWindow toolbar context menu

- gridsync/gui/color.py
- gridsync/gui/history.py
- gridsync/gui/invite.py
- gridsync/gui/main_window.py
- gridsync/gui/model.py
- gridsync/gui/status.py
- gridsync/gui/welcome.py
- misc/gridsync.spec
This PR adds basic support for macOS 10.14/Mojave's "dark mode", by explicitly disabling the `NSRequiresAquaSystemAppearance` app bundle setting (via "Info.plist") and fixing the most egregious color/stylesheet-related issues that prevented dark mode from being considered "supported" earlier.
There are additional optimizations that could be made here still (for example, by providing both "light" and "dark" variants of various image files/resources and loading the appropriate variant to further improve contrast as needed) but, for now, Mojave's dark mode should at least be usable.
Closes #213
> Add support for macOS Mojave's "dark mode"

- gridsync/gui/__init__.py
- gridsync/gui/main_window.py
- gridsync/gui/pixmap.py
- gridsync/gui/systray.py
In fulfillment of #226, this PR adds a `BadgedPixmap` class that overlays a red/circular "badge" onto an arbitrary pixmap that may contain text, at a relative size, and in a corner of the developer's choice. This is intended to be used to highlight the presence of pending or important information within the application, for example, like so (on macOS):
Note that this is mostly intended for future purposes; for now, a notification "badge" will only be displayed to signal a pending/unread "newscap" message (however, the same functionality may be used for other/additional purposes later on -- e.g., to communicate software updates, to highlight a magic-folder conflict, to remind users to export a Recovery Key, to notify of an expiring subscription to a commercial service provider, and so on).
> Add support for notification "badges"

- Makefile
- README.rst
- make.bat
- scripts/make_source_zip.py
- vagrantfiles/linux/Vagrantfile
- vagrantfiles/macos/Vagrantfile
- vagrantfiles/windows/Vagrantfile
This PR adds a set of `Vagrantfile`s that, in conjunction with VirtualBox, can be used to effectively "cross-compile" strongly forward-compatible Gridsync binaries for each supported platform (via the newly-added the `make vagrant-linux`, `make vagrant-macos` and `make vagrant-windows` commands). See the relevant section of the updated README for more information.
Closes #230
> Add support for building via Vagrant/VirtualBox

- Makefile
- make.bat
- misc/tahoe.spec
This PR updates and "pins" the frozen/PyInstaller builds of Tahoe-LAFS to a [much newer revision](https://github.com/tahoe-lafs/tahoe-lafs/commit/d6f0ce91233349759984b40fc721df7eef148f63) and removes a number of workarounds that appear to no longer be necessary as of the latest (3.5) release of PyInstaller.
Closes #237
> Update frozen/PyInstaller Tahoe-LAFS bundle

- gridsync/gui/main_window.py
Because this is poorly supported by Qt and can lead to a situation
in which the user cannot exit fullscreen mode by normal means.
Fixes #241
> Disable fullscreen mode on macOS

- .travis.yml
- Makefile
- README.rst
- gridsync/resources/config.txt
- scripts/make_appimage.py
- vagrantfiles/linux/Vagrantfile
This PR adds a rudimentary `make_appimage` script (called by the `make appimage` command) that uses [`linuxdeploy`](https://github.com/linuxdeploy/linuxdeploy/) to package [PyInstaller](https://www.pyinstaller.org/)-generated binaries into a single, standalone, executable Gridsync [AppImage](https://appimage.org/) file. Pending further testing and integration with CI/CD, this preliminarily allows for Gridsync AppImages to be offered alongside future releases, making it considerably easier for GNU/Linux users to install and run the application.
Closes #245
> Add support for deploying AppImage packages

- gridsync/streamedlogs.py
A guard against "RuntimeError: deque mutated during iteration"
Fixes #249
> Wrap log-buffer deque in list() during iteration

- .travis.yml
- Makefile
- scripts/make_appimage.py
- vagrantfiles/linux/Vagrantfile
This PR updates the `make_appimage` script to remove the seemingly-superfluous secondary copies of various libraries inserted by the `linuxdeploy` utility (replacing them instead with symlinks to the originals) and repack the resultant deduplicated AppDir with the vanilla/upstream `appimagetool` (in order to avoid re-insertion). On a CentOS7 buildbot-worker run, this shaved a whopping 43.6 MB off of the final AppImage file with no discernible issues or downsides (testing Debian 9, Debian 10, Fedora 29, and Fedora 30).
Closes #251
> Reduce AppImage filesize

- setup.py
The regexp doesn't handle all Python syntax.  For example, it is
broken by different styles of quoting.  Python itself is better at
parsing Python so use `exec`.
> Avoid a regexp in setup.py to find version number

- gridsync/__init__.py
> Don't call Versioneer's get_versions() if frozen

- gridsync/gui/welcome.py
- gridsync/resources/providers/demo-grid.json
This PR adds support for optionally specifying a "default" grid/connection via `config.txt` as follows:
```
[connection] 
default = demo-grid 
```
The presence of this option at runtime replaces the "Invite Code" field/widget on the welcome widow with a "Connect to <grid-name>" button which, when clicked, creates a `tahoe` node using the settings provided by the cheat code specified (thus, in the example above, a "Connect to Demo Grid" button will appear which, when clicked, will load the grid-configuration settings found at `gridsync/resources/providers/demo-grid.json`).
This (completely optional) setting is intended to be used for custom deployments of Gridsync -- for example, in the event of a user-testing session in which the "invite code" step might need to be skipped, or for …
> Allow a "default" grid/connection to be specified via config.txt

- gridsync/gui/main_window.py
- gridsync/gui/view.py
- gridsync/resources/config.txt
- gridsync/tor.py
- tests/test_tor.py
This PR adds support for disabling certain features via `config.txt` as follows:
```
[features] 
grid_invites = false  
invites = false                    
multiple_grids = false             
tor = false                          
```
Like in the case of #292, these options are intended to be used for custom deployments of Gridsync; by default, all disableable features are enabled.
> Make some functions disableable via config.txt

- gridsync/gui/status.py
- tests/gui/test_status.py
> Show grid name in status panel when "connected" (instead of connected/known node-count)

- requirements/gridsync.txt
A workaround for a Qt bug that breaks stylized buttons:
https://bugreports.qt.io/browse/QTBUG-84852
https://bugreports.qt.io/browse/QTBUG-84879
Fixes #298
> Pin/downgrade PyQt5 to 5.14.2 on macOS

- gridsync/gui/model.py
- gridsync/gui/status.py
- gridsync/gui/view.py
- gridsync/monitor.py
- gridsync/tahoe.py
- tests/gui/test_history.py
- tests/gui/test_status.py
- tests/test_monitor.py
This PR fixes #300, ensuring that no magic-folders will be marked as "Up to date" in the UI unless their corresponding `tahoe` client is sufficiently connected to the storage grid (as determined by whether it has connected to enough nodes to satisfy the `shares.happy` threshold _and_ has successfully completed a remote scan/crawl of the rootcap). The distinction between "Syncing" and "Scanning" has also been removed from the UI, since there was no functional difference between them from the user's perspective. Lastly, the total number of "connected" and "known" storage nodes -- along with the total amount of storage space available -- will now always be visible via the status label's tooltip (instead of via the now-removed "globe" button -- which served no other function).
Some additional …
> Fix status indicators when offline

- Makefile
- misc/tahoe.spec
This PR updates `make` targets and associated files to enable users of "Apple Silicon" (macOS arm64) machines to test and build the Gridsync application and it's dependencies from source. As per #322, support for macOS arm64 is presently very limited within the Python ecosystem and so this PR does _not_ aim to enable "native" compilation of arm64 binaries; instead it relies on Apple's "Rosetta" translation environment to produce x86_64 binaries that can both be built by and will run upon arm64 macOS machines.
> Build support for Apple Silicon

- .github/workflows/ci.yaml
- Makefile
- make.bat
- scripts/make_appimage.py
- scripts/make_zip.py
- scripts/provision_devtools.bat
- scripts/provision_devtools.sh
- scripts/test_determinism.py
- scripts/update_permissions.py
- scripts/update_timestamps.py
This PR adds a `make test-determinism` make target/command that sequentially "compiles" two PyInstaller bundles and compares their hashes against each other in order to verify the (local) reproducibility of the Gridsync build process. The files contained within the generated PyInstaller bundles are added (deterministically, with normalized file-permissions and timestamps) to an intermediate `Gridsync.zip` archive in order to facilitate further comparison and/or distribution of build outputs, while checks that do fail will have their outputs run through the `diffoscope` utility in order to identify any sources of variance between builds.
As it currently stands, this work is sufficient to demonstrate that PyInstaller "onedir" builds are indeed deterministic/reproducible on macOS _and_ …
> Reproducible builds for macOS and Windows

- gridsync/monitor.py
- gridsync/tahoe.py
- setup.py
- tests/test_monitor.py
It seems likely that https://github.com/PrivateStorageio/ZKAPAuthorizer/issues/110 will need to break some of the assumptions made by GridSync in its calculation of the number of ZKAPs available to be spent in the client.  In particular, the work there introduces the possibility of *unspendable* ZKAPs existing in the system.
In trying to understand how GridSync arrives at its understanding about how many spendable ZKAPs there are, I found it helpful to break `_parse_vouchers` out into a free function and slightly simplify it by separating the concerns of extracting information from the list of vouchers from the internal state management `ZKAPChecker` wants to do to be able to propagate change information elsewhere.
The changes in this PR are not meant to introduce any behavior changes. …
> Slightly clarify the logic for determining how many ZKAPs are available

- nix/gridsync.nix
- nix/pytesttwisted.nix
- nix/test_network.patch
It is idiomatic to run test suites as part of Nix package builds.  This enables that behavior.  The test suite passes on my local system:
```
===== 614 passed, 2 skipped, 2 deselected, 1 xpassed, 8 warnings in 7.05s ======
```
I would be happy to see this running on CI but I'm not sure if anyone else would.
> Run the test suite during Nix package build

- Makefile
- gridsync/resources/config.txt
- scripts/gpg.py
- scripts/signtool.py
This PR adds and makes use of a couple of basic wrappers/scripts around the `gpg` and `signtool` utilities, intended to facilitate the automation of signing- and release-related tasks -- especially on "rebranded" builds of the Gridsync application. More specifically, these scripts support reading additional signing-related parameters from `config.txt`, allowing, e.g., signing keys/identities to be declared in a single location. This allows individuals who wish to build and sign the application under a different identity to do so more easily -- namely, by updating the relevant values in `gridsync/resources/config.txt` (instead of hunting for and changing the previously-hardcoded values in the `Makefile`, batch scripts, etc.).
> Add GPG and Authenticode signing scripts

- gridsync/tahoe.py
- gridsync/util.py
- tests/test_tahoe.py
Fixes #414 
This brings CPU usage all the way down to 30% - comparable to where pulseaudio or Firefox idles :(  I guess that's what passes for industry standard now.
Maybe at some future point we can actually get rid of polling to address this the rest of the way.
> Fix the `await_ready` polling rate

- gridsync/tahoe.py
- tests/test_tahoe.py
Fixes #417 
These items are all optional.  It's not necessary to update ZKAPAuthorizer for these changes to be valid (they just won't do anything until ZKAPAuthorizer is updated).  There is still at least one more related ZKAPAuthorizer change to make before any of this will particularly help GridSync so it's not worth making that update yet.
> Handle new lease crawler configuration items

- gridsync/monitor.py
- tests/test_monitor.py
Fixes an `AttributeError` introduced in 407b57c44b96bae00b629595f84484e2735855e9 in the `last-redeemed` file handling code path.
> test `_ZKAPChecker._maybe_load_last_redeemed` and fix the AttributeError

- tox.ini
> Ensure `pip check` passes before calling PyInstaller

- gridsync/gui/view.py
- gridsync/magic_folder.py
- gridsync/rootcap.py
- gridsync/tahoe.py
- tests/integration/test_magic_folder_integration.py
- tests/integration/test_rootcap_integration.py
Fixes #437 
Also fixes two adjacent/related issues discovered along the way:
* Leaving a magic-folder now also immediately removes that folder name from the internal Gridsync active folders list (`MagicFolder.magic_folders`). Previously, this state was only being updated when `MagicFolderMonitor.do_check` was being called -- resulting in a temporary situation in which the "Folders" view's context menu could display actions that were invalid for the given folder type (for example, offering the "stop syncing" action for a folder that was no longer active/syncing).
* Removing a folder backup now also immediately removes that folder from the internal Gridsync known backups list (`MagicFolder.remote_magic_folders`). Likewise, this state was also only being updated when …
> Make leaving magic-folders (and removing folder backups) idempotent

- gridsync/__init__.py
- gridsync/core.py
- gridsync/gui/main_window.py
- gridsync/gui/model.py
- gridsync/gui/preferences.py
- gridsync/resources/config.txt
- gridsync/util.py
- tests/test_util.py
This PR implements three small measures aimed at encouraging users to keep the application running in the background for the purposes of increasing the likelihood of successful lease-renewal. These consist of:
* _If the user is connected to at least one ZKAPAuthorizer-enabled storage grid_, upon exiting the application, display a warning (informing users that the application will stop renewing data if it is not running -- and that doing so over extended periods can result in data-loss) and require user-confirmation in order to proceed.
* _If the `[default] autostart` value is set to `true` in `config.txt`_, enable autostart by default, launching the application automatically upon login.
* _if the `[default] autostart` value is set to `true` in `config.txt`_, display a warning and require …
> Encourage lease-renewal

- gridsync/setup.py
- gridsync/tahoe.py
- gridsync/zkapauthorizer.py
- tests/integration/test_zkapauthorizer_plugin.py
- tests/test_tahoe.py
- tests/test_zkapauthorizer.py
ZKAPAuthorizer's new backup API is sufficiently different from the old one that I'm bumping the API version number.
In preparation, here's a refactoring that removes the duplication of the string "privatestorageio-zkapauthz-v1" throughout GridSync and centralizes the definition of the supported API version of ZKAPAuthorizer.  The value is left as-is for now.  The likely path forward is a future PR that switches GridSync to the new backup API and bumps the version in the string to 2.
> define the plugin name once, re-use it most everywhere else

- gridsync/gui/charts.py
- gridsync/gui/main_window.py
This PR provides a number of small UI adjustments (to layout margins, font-size, window dimensions) for the purposes of preventing the labels in the legend of the "Storage-time" chart from becoming truncated by default or common values:
In the event that the labels _do_ become truncated (e.g., due to especially large values), tooltips are now available to make the underlying values visible without needing to resize the main window.
Fixes #453
> Adjust Storage-time chart legend

- Makefile
- requirements/gridsync-base.txt
- requirements/gridsync-platform.txt
- requirements/lint.txt
- requirements/magic-folder-base.txt
- requirements/pyinstaller-base.txt
- requirements/tahoe-lafs-base.txt
- requirements/test.in
- requirements/test.txt
Just a minor development quality-of-life improvement: allow the `pytest-xvfb` plugin to set up a virtual framebuffer as needed, removing the need to wrap/call `tox` with `xvfb-run -a` while testing on GNU/Linux.
> Add and use `pytest-xvfb` plugin

- gridsync/gui/view.py
PR #457 disallowed adding empty folders in order to compensate for some
limitations with the Magic-Folder "status" API. Those limitations have
since been resolved (specifically, by the addition of  `last-scan` and
`last-poll` fields), making it possible to make determinations about
the sync status of empty folders. Accordingly, this change reverts #457,
allowing empty Magic-Folders to be added again (without those folders
appearing to be stuck in a "Loading..." state).
> Allow adding Magic-Folders for empty directories

- gridsync/desktop.py
This PR makes some minor adjustments to `desktop.notify` with the aim of providing working fallback mechanisms for desktop environments that don't support traditional desktop notifications:
* On Linux-like systems, actually catch and handle exceptions raised by txbus calls in the event that, e.g., the host operating system lacks DBus (these exceptions were previously uncaught due to missing `yield` statement...)
* Show a popup message via `QSystemTray.showMessage` iff the systray actually supports messages
* Fall back to logging the message, if all else fails
> Desktop notification fallbacks

- gridsync/supervisor.py
- gridsync/system.py
- gridsync/util.py
- tests/integration/test_magic_folder_integration.py
- tests/test_supervisor.py
The `Supervisor` test `test_supervisor_restarts_process_when_killed` has been [failing intermittently](https://github.com/gridsync/gridsync/runs/6761540545?check_suite_focus=true#step%3A5%3A63=) on Windows, for some time -- perhaps because 3 seconds isn't enough time for a process to be killed on GitHub Actions' Windows runners, or perhaps because filesystem operations are extra slow on GHA, or perhaps because Windows re-uses PIDs more eagerly than other operating systems... In any case, it happens frequently enough to be a source of developer-frustration and, Windows-specific issues aside, it isn't a very good test anyway:
```
================================== FAILURES ===================================
________________ test_supervisor_restarts_process_when_killed _________________ …
```
> Fix intermittently-failing Supervisor "restart" test

- .github/workflows/ci.yaml
The merge HEAD is not guaranteed to be stable across time - even the time that
passes between two jobs in the same workflow running their checkout steps.
> Check out the branch HEAD instead of the merge HEAD

- gridsync/zkapauthorizer.py
Fixes #489
(cc @makeworld-the-better-one)
> Fix `converted_batch_size`; make `value` a kwarg

- gridsync/gui/pixmap.py
- gridsync/gui/systray.py
- setup.cfg
- tests/gui/test_pixmap.py
Fixes #496.
Also adds type annotations and some basic tests for the rest of the "pixmap" module.
> Fix `QRect` TypeError introduced by PyQt5 5.15.7

- docs/verifying-signatures.md
The current "`pool.sks-keyservers.net` keyserver service is deprecated and service reliability should not be expected."
Source: https://unix.stackexchange.com/questions/656205/sks-keyservers-gone-what-to-use-instead
> Update GPG keyserver for signature verification

- Vagrantfile
This PR corrects an oversight introduced by #514 in which a workaround for macOS environments was also mistakenly being applied to non-macOS environments, causing the provisioning of those (non-macOS) environments to fail. With this change in place, the "macOS.nvram" will only attempt to be copied from macOS (11 and 12) boxes.
> Update Vagrantfile (again)

- requirements/gridsync-base.txt
- requirements/lint.txt
- requirements/magic-folder-base.txt
- requirements/pyinstaller-base.txt
- requirements/tahoe-lafs-base.txt
Magic-Folder 22.8.0 has just been released, fixing [an issue that caused downloads to fail for files with shared content](https://github.com/LeastAuthority/magic-folder/issues/662). This PR updates Gridsync's Magic-Folder dependency to 22.8.0 (along with other minor dependency updates).
> Update Magic-Folder to version 22.8.0

- .github/workflows/ci.yaml
- CONTRIBUTING.rst
- flake.lock
- flake.nix
This makes `nix develop` work with a recent-enough version of Nix (with flakes enabled).  The resulting environment contains enough stuff for `tox -e py39,integration,lint` to succeed.
Also included is a new GitHub Actions job to do these things on CI, mostly to ensure they keep working (and so remain useful for development work on GridSync on NixOS or with Nix tools on other OS).
> Add Nix-based development shell and related CI

- gridsync/gui/welcome.py
- gridsync/invite.py
- gridsync/setup.py
- tests/test_setup.py
> Convert setup.py to `async def`

- .github/workflows/ci.yaml
- Vagrantfile
- scripts/provision_buildbot-worker.sh
- scripts/provision_devtools.bat
- scripts/provision_devtools.sh
Just some fairly minor updates to the project `Vagrantfile` and associated scripts to a) facilitate provisioning buildbot-workers on newer, zsh-using versions of macOS and b) bump the python interpreter version (from 3.10.4 to 3.10.6).
> Update `Vagrantfile`, provisioning scripts

- gridsync/core.py
- gridsync/gui/view.py
- gridsync/magic_folder.py
- gridsync/monitor.py
- gridsync/news.py
- gridsync/setup.py
- gridsync/tahoe.py
- gridsync/util.py
- gridsync/zkapauthorizer.py
- tests/conftest.py
- tests/integration/test_magic_folder_integration.py
- tests/integration/test_rootcap_integration.py
- tests/integration/test_tahoe_integration.py
- tests/test_monitor.py
- tests/test_news.py
- tests/test_setup.py
- tests/test_tahoe.py
Fixes #523 
Please note `test_tahoe_stop_locked`.  I'm not sure if this kind of global reactor interaction is correct with pytest_twisted, and even if so if it is the preferred style in GridSync's tests.  However, I'm also not sure what else to do there.
The commits are almost all self-contained changesets that address one function from `tahoe.py` completely throughout the codebase, in case that helps with review.
> Convert gridsync/tahoe.py to `async def`

- tests/test_supervisor.py
`until` polls with fairly low resolution.  If the supervisor managed to
receive exit notification and launch a new process between two consecutive
polls for `is_running() == False` the test would miss the stopped condition
entirely and never complete (or rather, time out after 10 seconds).
Now just wait for the supervisor to report the pid has changed and assert the
process ends in the desire state (running).
> Fix race condition between test and supervisor restart

- gridsync/gui/status.py
- gridsync/gui/usage.py
- gridsync/util.py
- tests/test_util.py
A minor refactoring and improvement of https://github.com/gridsync/gridsync/pull/535 to display fuzzier "Centuries" label for extremely large "days remaining" / "expected expiry" values.
> Improve "days remaining" calculation

- gridsync/tahoe.py
- tests/test_tahoe.py
> Fix crash caused by attempting to redact/filter non-existent rootcap from logs

- gridsync/core.py
- gridsync/tahoe.py
- tests/test_tahoe.py
Recent changes in both [Magic-Folder](https://github.com/LeastAuthority/magic-folder) and [ZKAPAAuthorizer](https://github.com/PrivateStorageio/ZKAPAuthorizer) have broken compatibility with older Tahoe-LAFS and Gridsync configurations: Specifically, the "magic-folder" feature present in earlier versions of Tahoe-LAFS has been [removed as of Tahoe-LAFS version 1.15](https://github.com/tahoe-lafs/tahoe-lafs/blob/f9ddd3b3bedf692ffdf598d9def96b3c79097602/NEWS.rst#removed-features-2) (having been split off into a [standalone project](https://github.com/LeastAuthority/magic-folder) with a different configuration format), while ZKAPAuthorizer's [newer backup/restore system](https://github.com/PrivateStorageio/ZKAPAuthorizer/issues/235) has removed the older "v1" endpoints used by previous …
> Display user-facing error messages for incompatible/out-of-date Tahoe-LAFS configurations

- pyinstaller.spec
> Ensure recreation of "resources" (sub)dir in PyInstaller bundles

- pyinstaller.spec
- scripts/make_appimage.py
> Exclude `libwayland-client` from PyInstaller bundle

- scripts/codesign.py
- scripts/extract_dmg.py
- scripts/get_yum_packages.py
- scripts/gpg.py
- scripts/irc-notify.py
- scripts/make_appimage.py
- scripts/make_archive.py
- scripts/make_installer.py
- scripts/make_source_tarball.py
- scripts/make_zip.py
- scripts/notarize.py
- scripts/sha256sum.py
- scripts/signtool.py
- scripts/test_determinism.py
- scripts/update-github-repo
- scripts/update_permissions.py
- scripts/update_timestamps.py
The presence of `python3`-invoking shebang lines (`#!/usr/bin/env python3`) atop some of the scripts under the "scripts/" dir was causing issues for newly provisioned Windows 10 buildbot-workers (whereby the presence of the line would lead Windows to interrupt execution and ask to install Python from the Microsoft Store, even when invoking the scripts from Python itself). This appears to be a problem stemming from changes to Python 3.11's  `py` wrapper as per [this SO post](https://stackoverflow.com/questions/74349036/behavior-change-in-py-exe-on-recent-versions-of-python-for-windows) since the issue does not occur with Python 3.10's `py` wrapper. 
This PR removes the problematic lines, restoring the functionality of the scripts, even when invoked under Python 3.11.
Fikes #654
> Remove unused shebang lines from python CI scripts

- gridsync/gui/usage.py
- gridsync/gui/view.py
- gridsync/magic_folder.py
- gridsync/util.py
- tests/test_util.py
This PR updates the language used in Magic-Folder-related error messages to be a little less technical for end-users (while still preserving technical details should they be required). Specifically:
* Language in the form of "An exception was raised..." is now "An error occurred...".
* For Magic-Folder errors that provide a `reason` field, the provided `reason` value will be now take priority and be displayed in place of the previously-shown technical information (about, e.g., which HTTP method was used, the status code, etc. for Magic-Folder web API errors).
* Full tracebacks (containing the information previously shown above) are now available via the "Show details..." button.
> Improve language in user-facing Magic-Folder invite errors

- pyproject.toml
- requirements/gridsync-base.txt
- requirements/gridsync.in
Hello @crwood,
I hope you're doing well! I've just opened this pull request that proposes the removal of the unused `hyperlink` direct dependency from the `pyproject.toml` and `requirements/gridsync.in` configuration files. It's part of an ongoing research endeavor focusing on the identification and elimination of code bloat within software projects. Your insights on this would be really valuable.
The `hyperlink` library was introduced  in  0a032c9. However it appears to be unused in the source code. It was added on the grounds that it was required transitively by `twisted `.
Therefore, when `gridsync` is installed through pip (e.g. `pip install -e .`), pip will automatically resolve `hyperlink` through `twisted`.
Removing this direct dependency will  mitigate potential security risks …
> Remove unused dependency: hyperlink

- .github/workflows/ci.yaml
- Makefile
This PR removes the deprecated `macos-11` runner from the GitHub Actions CI matrix, and adds `macos-13` and `ubuntu-24.04`.
Closes #700
> Update GitHub Actions configuration

- requirements/test.in
- requirements/test.txt
`pytest-twisted` 1.14.2 was just released, [fixing](https://github.com/pytest-dev/pytest-twisted/pull/178) the issue that was seemingly causing Gridsync's integration tests to hang when using pytest 8.2 under `tox`.
Closes #690
> Support Pytest 8.2+

- .github/workflows/ci.yaml
Closes https://github.com/gridsync/gridsync/issues/728
> Remove deprecated `windows-2019` runner from GitHub Actions matrix
